import { ArrowDown, ArrowRight, ArrowUpRight, Compass, MoveUpRight } from 'lucide-react'
import { Link } from 'react-router'
import { useEffect } from 'react'
import { services } from './requestSchema'
import './aviation.css'

export default function AviationPage() {
  useEffect(() => { document.title = 'HRL Aviation · A new chapter at Harlingen' }, [])
  return <div className="aviation">
    <div className="av-masthead av-wrap"><Link to="/aviation" className="av-wordmark"><Compass size={23} strokeWidth={1.2} /> HRL AVIATION</Link><span>HARLINGEN, TEXAS</span><Link to="/aviation/portal">Customer portal <ArrowUpRight size={14} /></Link></div>
    <section className="av-hero">
      <div className="av-wrap av-hero-layout">
        <div className="av-hero-copy"><p className="av-eyebrow"><span className="av-dot" /> A NEW CHAPTER AT HRL · PRELAUNCH</p><h1>A little closer<br />to <em>everywhere.</em></h1><p className="av-intro">A considered approach to aviation in the Rio Grande Valley. From the journey above to the details on the ground.</p><Link className="av-button av-button-dark" to="/aviation/request?service=flight&step=details">Plan a flight request <ArrowUpRight size={19} /></Link><p className="av-fine">Requests only. Every service is subject to review and future availability.</p></div>
        <div className="av-flight-art" aria-hidden="true"><div className="av-art-sun" /><div className="av-art-coast" /><div className="av-art-land" /><div className="av-art-runway"><span>17</span><i /><i /><i /><i /><i /><i /><b>HRL</b></div><svg viewBox="0 0 600 650" className="av-art-path"><path d="M -40 590 C 310 620 750 450 485 200 S 120 120 180 -80" fill="none" stroke="currentColor" strokeWidth="1.3" strokeDasharray="4 7"/><circle cx="400" cy="519" r="7" fill="currentColor"/><circle cx="400" cy="519" r="17" fill="none" stroke="currentColor" /></svg><div className="av-art-label">THE VALLEY, WITH A WIDER HORIZON<span>HRL / SOUTH TEXAS</span></div><span className="av-art-caption">An illustrated perspective</span></div>
      </div><a className="av-scroll" href="#possibilities">Explore the possibilities <ArrowDown size={14} /></a>
    </section>
    <section className="av-process av-wrap"><p className="av-eyebrow">THOUGHTFULLY COORDINATED</p><div><h2>One conversation.<br /><em>A clearer journey.</em></h2><p>The vision is simple: bring flight planning, workspace, and arrival services into one place. Today, it begins with an inquiry.</p></div><ol className="av-steps"><li><span>01</span><h3>Your request</h3><p>Tell us what you have in mind. Receive a reference for your saved inquiry.</p></li><li><span>02</span><h3>A personalized quote</h3><p>Scope, options, and pricing follow review, when providers and availability are established.</p></li><li><span>03</span><h3>Confirmed by the operator</h3><p>An itinerary requires explicit operator confirmation. A request, quote, or payment is not an inventory hold.</p></li></ol></section>
    <section id="possibilities" className="av-services"><div className="av-wrap"><div className="av-section-heading"><div><p className="av-eyebrow">THE POSSIBILITIES</p><h2>Beyond the flight.</h2></div><p>Five ways to begin.<br />All currently at the inquiry stage.</p></div><div className="av-service-list">{Object.entries(services).map(([key, service], index) => <Link key={key} className="av-service-row" to={`/aviation/request?service=${key}&step=details`}><span className="av-number">0{index + 1}</span><div><span className="av-eyebrow">{service.eyebrow}</span><h3>{service.label}</h3></div><p>{service.description}</p><ArrowUpRight size={25} strokeWidth={1.2} /></Link>)}</div></div></section>
    <section className="av-place av-wrap"><div className="av-place-drawing" aria-hidden="true"><div className="av-grid" /><div className="av-hangar"><div /><div /><div /></div><span>SPACE TO IMAGINE WHAT COMES NEXT</span><small>Concept illustration · not a site plan</small></div><div><p className="av-eyebrow">ROOTED IN THE RIO GRANDE VALLEY</p><h2>Room for<br /><em>what’s next.</em></h2><p>We are exploring one or two aviation buildings near HRL, adjacent to Jet House HRL, with potential office and hangar space.</p><p>Plans remain preliminary. This proposal does not imply ownership of, or a partnership with, the existing Jet House facility.</p><Link className="av-text-link" to="/aviation/request?service=leasing&step=details">Register your space requirements <ArrowRight size={18} /></Link></div></section>
    <section className="av-closing"><div className="av-wrap"><p className="av-eyebrow">LET’S START WITH YOUR PLANS</p><h2>Where would you<br /><em>like to go?</em></h2><Link className="av-button" to="/aviation/request?service=flight&step=details">Begin an inquiry <MoveUpRight size={20} /></Link><p>HRL Aviation is a working name for a prelaunch concept.<br />No fleet, operating authority, inventory, or service availability is represented.</p></div></section>
  </div>
}
