import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router'
import { ArrowDown, ArrowRight, ArrowUpRight, Building2, CarFront, Compass, GraduationCap, Pause, Plane, Play, Sparkles } from 'lucide-react'
import { gsap } from 'gsap'
import { useGSAP } from '@gsap/react'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import RegionalExplorer from './RegionalExplorer'
import { useAviationMotion } from './useAviationMotion'
import './aviation.css'
import './aviation-experience.css'

gsap.registerPlugin(useGSAP, ScrollTrigger)

const offerings = [
  { id: 'flight', title: 'Flight coordination', short: 'The journey', icon: Plane, headline: 'Every great journey starts with a conversation.', description: 'Your destination. Your timing. Your preferences. Start a flight request so the right details are in place for a personalized quote when operators and availability are established.', action: 'Plan a flight request', note: 'Request → personalized quote → operator confirmation', image: 'harlingen-aerial', alt: 'Northern Harlingen photographed on departure from Valley International Airport', caption: 'Above Harlingen, Texas · RobertKixmiller · CC BY-SA 4.0' },
  { id: 'leasing', title: 'Office & hangar space', short: 'Your home base', icon: Building2, headline: 'A home for what comes next.', description: 'We are exploring one or two aviation buildings near HRL, adjacent to Jet House HRL. Share your office and hangar requirements to help shape the possibilities.', action: 'Explore space requirements', note: 'Preliminary plans. No space or lease availability is offered.', image: 'harlingen-aerial', alt: 'Aerial context photograph of northern Harlingen, not a proposed site or available property', caption: 'Harlingen regional context · not a site plan or property offering' },
  { id: 'car', title: 'Arrival by car', short: 'The next mile', icon: CarFront, headline: 'Keep your plans moving after touchdown.', description: 'An island weekend or a meeting in the Valley. Tell us your arrival details, destination, and vehicle preferences for review when service partners are established.', action: 'Request arrival coordination', note: 'Vehicles, inventory holds, and checkout are not yet available.', image: 'padre', alt: 'The beach and dunes of South Padre Island', caption: 'South Padre Island · Spheroidite · CC BY-SA 4.0' },
  { id: 'training', title: 'Learn to fly', short: 'A new perspective', icon: GraduationCap, headline: 'Look up. Then imagine yourself there.', description: 'From your first curiosity about flying to your next training goal, tell us where you would like to begin. Register interest while the flight-school concept takes shape.', action: 'Share your flying goals', note: 'Interest only. No school, instructor, or training slot is confirmed.', image: 'harlingen-aerial', alt: 'A view across northern Harlingen from a departing passenger aircraft', caption: 'Above Harlingen, Texas · RobertKixmiller · CC BY-SA 4.0' },
  { id: 'detailing', title: 'Aircraft detailing', short: 'Every detail', icon: Sparkles, headline: 'Care that begins with the details.', description: 'Share your aircraft type, location, and interior or exterior care needs. Each inquiry begins with a review of scope and future provider availability.', action: 'Discuss aircraft care', note: 'No appointment or provider is confirmed by this inquiry.', image: 'harlingen-aerial', alt: 'Northern Harlingen seen from the air', caption: 'Harlingen regional photograph · no fleet or provider represented' },
] as const

export default function AviationPage() {
  const root = useRef<HTMLDivElement>(null)
  const [service, setService] = useState(0)
  const { motion, reduced, paused, toggle } = useAviationMotion()
  const current = offerings[service]
  const ServiceIcon = current.icon
  useEffect(() => { document.title = 'HRL Aviation · A wider horizon, rooted in Harlingen' }, [])
  useGSAP(() => {
    if (!motion) return
    gsap.from('.av-hero-line > span', { yPercent: 105, duration: 1.1, stagger: .15, ease: 'power3.out' })
    gsap.from('.av-hero-enter', { opacity: 0, y: 16, duration: .85, stagger: .1, delay: .3, ease: 'power2.out' })
    gsap.to('.av-hero-photo', { yPercent: 14, scale: 1.05, ease: 'none', scrollTrigger: { trigger: '.av-cinema', start: 'top top', end: 'bottom top', scrub: .6 } })
    gsap.utils.toArray<HTMLElement>('.av-reveal').forEach(element => {
      gsap.from(element, { y: 28, opacity: .2, duration: .8, ease: 'power2.out', scrollTrigger: { trigger: element, start: 'top 92%', once: true } })
    })
    gsap.from('.av-process-line', { scaleX: 0, transformOrigin: 'left', ease: 'none', scrollTrigger: { trigger: '.av-journey', start: 'top 75%', end: 'bottom 75%', scrub: .4 } })
  }, { scope: root, dependencies: [motion], revertOnUpdate: true })

  return <div className={`aviation av-experience${motion ? '' : ' av-motion-off'}`} ref={root}>
    <section className="av-cinema" aria-labelledby="aviation-title">
      <picture className="av-hero-photo"><source media="(max-width: 700px)" srcSet="/aviation/harlingen-aerial-900.webp" /><img src="/aviation/harlingen-aerial-2200.webp" alt="Northern Harlingen, Texas, photographed from a flight departing Valley International Airport" width="2200" height="1650" fetchPriority="high" /></picture>
      <div className="av-hero-shade" />
      <div className="av-cinema-content av-wrap">
        <div className="av-hero-top av-hero-enter"><Link to="/aviation" className="av-wordmark"><Compass size={27} strokeWidth={1} /><span>HRL AVIATION<small>HARLINGEN, TEXAS</small></span></Link><span className="av-prelaunch"><i /> A NEW CHAPTER / PRELAUNCH</span></div>
        <div className="av-hero-main"><p className="av-eyebrow av-hero-enter">SOUTH TEXAS. AN ENTIRELY NEW PERSPECTIVE.</p><h1 id="aviation-title"><span className="av-hero-line"><span>Rooted here.</span></span><span className="av-hero-line"><span><em>Going beyond.</em></span></span></h1><div className="av-hero-bottom av-hero-enter"><p>From your next departure to what comes after touchdown. A new vision for aviation in the Rio Grande Valley.</p><Link className="av-button av-button-gold" to="/aviation/request?service=flight&step=details">Start a flight request <ArrowUpRight size={20} /></Link></div></div>
        <div className="av-hero-foot av-hero-enter"><a href="#the-valley" className="av-explore-link"><span className="av-round"><ArrowDown size={18} /></span>EXPLORE OUR PART OF THE WORLD</a><div className="av-photo-credit"><span>ACTUAL VIEW / NORTHERN HARLINGEN / 2022</span><a href="https://commons.wikimedia.org/wiki/File:Aerial_View_Of_The_Northern_Part_Of_Harlingen,_TX_08202022_1.jpg" target="_blank" rel="noreferrer">RobertKixmiller</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a> · Display crop</div></div>
      </div>
      <div className="av-hero-coordinate" aria-hidden="true">26.23° N — 97.65° W</div>
    </section>

    <div className="av-flight-strip"><div className="av-wrap"><span><i /> NOW TAKING PRELAUNCH INQUIRIES</span><p>A request starts the conversation. It does not reserve a service.</p><button type="button" onClick={toggle} disabled={reduced} aria-pressed={paused || reduced} aria-label={reduced ? 'Motion off: system preference' : paused ? 'Enable motion' : 'Pause motion'}>{paused || reduced ? <Play size={13} /> : <Pause size={13} />}{reduced ? 'Reduced motion' : paused ? 'Motion off' : 'Pause motion'}</button></div></div>

    <section className="av-introduction av-wrap av-reveal"><p className="av-eyebrow">A VISION FOR THE JOURNEY, AND EVERYTHING AROUND IT.</p><h2>More than a destination.<br /><em>A different way to arrive.</em></h2><div><span className="av-section-index">01 — THE EXPERIENCE</span><p>Flight requests. A future home base. A thoughtful arrival. We’re bringing the pieces together around HRL, with a clear path from your first inquiry to what comes next.</p></div></section>

    <section className="av-offerings av-wrap" id="services" aria-labelledby="services-heading"><div className="av-offering-header av-reveal"><p className="av-eyebrow">BUILT AROUND YOUR PLANS</p><h2 id="services-heading">Make it <em>your own.</em></h2></div><div className="av-offering-layout"><div className="av-offering-menu" role="group" aria-label="Explore aviation services">{offerings.map((item, index) => <button key={item.id} aria-pressed={index === service} aria-controls="selected-service" onClick={() => setService(index)}><span>0{index + 1}</span><div><small>{item.short}</small><strong>{item.title}</strong></div><ArrowUpRight size={21} strokeWidth={1.3} /></button>)}<p>Five ways to begin.<br />Each starts with a request.</p></div><article className="av-offering-detail" id="selected-service" aria-live="polite" aria-atomic="true"><img key={current.image} src={`/aviation/${current.image}-1600.webp`} alt={current.alt} width="1600" height="1100" loading="lazy" decoding="async" /><div className="av-offering-shade" /><div className="av-offering-detail-content"><div className="av-service-symbol"><ServiceIcon size={36} strokeWidth={1} /><span>0{service + 1} / HRL</span></div><p className="av-eyebrow">{current.short} / IN DEVELOPMENT</p><h3>{current.headline}</h3><p>{current.description}</p><Link className="av-button av-button-gold" to={`/aviation/request?service=${current.id}&step=details`}>{current.action}<ArrowUpRight size={18} /></Link><small>{current.note}</small><p className="av-service-caption">{current.caption} · <a href="#image-credits">Image credits</a></p></div></article></div></section>

    <RegionalExplorer motion={motion} />

    <section className="av-journey" aria-labelledby="journey-heading"><div className="av-wrap"><div className="av-section-heading av-reveal"><div><p className="av-eyebrow">A CLEAR PATH FORWARD</p><h2 id="journey-heading">Considered at<br /><em>every step.</em></h2></div><p>The vision is personal service.<br />The process starts with clarity.</p></div><div className="av-process-track"><div className="av-process-line" /></div><ol className="av-journey-steps"><li className="av-reveal"><span>01 / REQUEST</span><h3>Tell us your plans.</h3><p>Share the details that matter. Your inquiry is saved with a reference number to keep.</p><Link to="/aviation/request?service=flight&step=details">Begin an inquiry <ArrowRight size={16} /></Link></li><li className="av-reveal"><span>02 / PERSONALIZE</span><h3>Shape the possibilities.</h3><p>Following review, a personalized quote can bring together scope, options, and pricing when providers and availability are established.</p></li><li className="av-reveal"><span>03 / CONFIRM</span><h3>Know what’s confirmed.</h3><p>A flight itinerary requires explicit operator confirmation. A request, quote, or payment does not itself hold inventory.</p></li></ol></div></section>

    <section className="av-future av-wrap av-reveal"><div className="av-future-marker" aria-hidden="true"><span>HRL</span><Compass size={130} strokeWidth={.35} /><small>THE NEXT CHAPTER</small></div><div><p className="av-eyebrow">SPACE FOR AMBITION</p><h2>A new chapter.<br /><em>On familiar ground.</em></h2><p>One or two potential aviation buildings near HRL. Office and hangar space shaped around the people who will use it. A vision beginning with local conversations.</p><Link className="av-text-link" to="/aviation/request?service=leasing&step=details">Tell us what you need <ArrowUpRight size={18} /></Link><small>Preliminary plans adjacent to Jet House HRL. No ownership of, or partnership with, the existing Jet House facility is represented.</small></div></section>

    <section className="av-final-invitation"><img src="/aviation/padre-1600.webp" alt="Open sky and Gulf shoreline at South Padre Island" width="1600" height="715" loading="lazy" /><div className="av-wrap av-reveal"><p className="av-eyebrow">YOUR NEXT CHAPTER STARTS WITH A CONVERSATION.</p><h2>Where do we<br /><em>begin?</em></h2><Link className="av-button av-button-gold" to="/aviation/request?service=flight&step=details">Let’s talk about your plans <ArrowUpRight size={20} /></Link><p>Harlingen, Texas. A wider horizon.</p></div></section>

    <div className="av-colophon av-wrap"><div><Link className="av-wordmark" to="/aviation"><Compass size={25} strokeWidth={1} /> HRL AVIATION</Link><p>A working name. A local vision. In development.<br />No fleet, operating authority, inventory, or service availability is represented.</p></div><Link className="av-text-link" to="/aviation/portal">The future customer portal <ArrowUpRight size={16} /></Link><details id="image-credits"><summary>Photography & map credits</summary><p>Harlingen aerial: <a href="https://commons.wikimedia.org/wiki/File:Aerial_View_Of_The_Northern_Part_Of_Harlingen,_TX_08202022_1.jpg" target="_blank" rel="noreferrer">RobertKixmiller, 2022</a>. South Padre Island: <a href="https://commons.wikimedia.org/wiki/File:South_Padre_Island_beach_panorama.jpg" target="_blank" rel="noreferrer">Spheroidite, 2022</a>. Both <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a>; resized, compressed, and cropped with display overlays. Image adaptations remain CC BY-SA 4.0. Laguna Atascosa: <a href="https://commons.wikimedia.org/wiki/File:Laguna_Atascosa_NWR_inlet_(5121525224).jpg" target="_blank" rel="noreferrer">USFWS, 2003</a>, public domain / <a href="https://creativecommons.org/licenses/by/2.0/" target="_blank" rel="noreferrer">CC BY 2.0</a>. Map: <a href="https://www.naturalearthdata.com/" target="_blank" rel="noreferrer">Natural Earth</a>, public domain. Photographs provide regional context and do not imply endorsement, ownership, current conditions, or service availability.</p></details></div>
  </div>
}
